export const equal = '=';
export const notEqual = '<>';
export const greaterThan = '>';
export const greaterThanOrEqual = '>=';
export const lessThan = '<';
export const lessThanOrEqual = '<=';
export const startsWith = 'STARTS_WITH';
export const contains = 'CONTAINS';
export const endsWith = 'ENDS_WITH';
export const _in = 'IN';
export const notIn = 'NOT IN';
export const between = 'BETWEEN';
export const notBetween = 'NOT BETWEEN';
export const isNull = 'IS NULL';
export const isNotNull = 'IS NOT NULL';
